export const students = [
  {
    class: "SKG",
    password: "BMHSAADH",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSAARA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSABDU",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSADLI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSALSH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSAMOG",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSANU",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSANUG",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSARUJ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "SKG",
    password: "BMHSARUN",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSASWA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSBHAR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSBLES",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSDAPH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSDARS",
    dob:" ",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSDHAR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSDHIY",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSDIAA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "SKG",
    password: "BMHSEVAN",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSFATH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSFREI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSHARI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSIVON",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSJAYA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSJAZL",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSJELI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSJENI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSJESH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "SKG",
    password: "BMHSJOVI",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSKART",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSKEER",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSLOHI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMAHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMAHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
    {
    class: "SKG",
    password: "BMHSMANU",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMAVI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMOUS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMUKI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSMUTH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSNAVA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "SKG",
    password: "BMHSNAVY",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSNIKS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSNIVI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSPOOV",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSPRAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSRAGA",
    dob:" ",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSRAYA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSRITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSRITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "SKG",
    password: "BMHSRUDH",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSAAI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSAID",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSAMF",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSANJ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSANJ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSHAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSHAS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSHER",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSHIV",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "SKG",
    password: "BMHSSIDH",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSRIT",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSUBU",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSURJ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSSWAT",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSTHAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSTHIL",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSVARU",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSYUVA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  }
]