export const students = [
  {
    class: "11",
    password: "BMHSAARA",
    dob: "2009-07-02",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class: "11",
    password: "BMHSABIN",
    dob: "2009-12-10",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class: "11",
    password: "BMHSABIS",
    dob: "2009-12-23",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSAMAR",
    dob:"2009-07-30",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSANUS",
    dob:"2009-04-21",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSASHO",
    dob:"2009-04-26",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSBHAR",
    dob:"2009-08-13",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "11",
    password: "BMHSCHAR",
    dob: "2009-11-06",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSCHAR",
    dob:"2009-07-14",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSDANA",
    dob:"2009-08-30",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSDARS",
    dob:"2009-11-15",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSDEEP",
    dob:"2009-11-29",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "11",
    password: "BMHSDENN",
    dob: "2009-08-19",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSDESH",
    dob:"2008-12-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSFELI",
    dob:"2010-02-16",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSGENI",
    dob:"2009-12-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSHAAS",
    dob:"2010-08-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSHANE",
    dob:"2009-06-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSJESS",
    dob:"2009-08-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSJEYA",
    dob:"2010-02-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSKARA",
    dob:"2009-06-14",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSKAVI",
    dob:"2009-01-28",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSKAVI",
    dob:"2009-07-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSKAVI",
    dob:"2009-07-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSLING",
    dob:"2010-01-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSMEGA",
    dob:"2009-11-05",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSMOHA",
    dob:"2010-02-26",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSNALI",
    dob:"2009-04-09",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "11",
    password: "BMHSNEGA",
    dob: "2010-01-11",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSNIDH",
    dob:"2009-12-18",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSNITH",
    dob:"2009-09-05",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSNIVE",
    dob:"2009-12-15",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSPONS",
    dob:"2009-05-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSPRAD",
    dob:"2009-03-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSPRAT",
    dob:"2009-02-28",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSPRAV",
    dob:"2009-06-02",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSRAJA",
    dob:"2009-06-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSRITH",
    dob:"2009-12-12",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSRITH",
    dob:"2009-03-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSANJ",
    dob:"2009-05-07",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSANT",
    dob:"2009-06-23",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSARA",
    dob:"2009-03-16",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSHAR",
    dob:"2009-04-23",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSILV",
    dob:"2010-01-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSRIR",
    dob:"2009-10-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"11",
    password:"BMHSSURY",
    dob:"2009-08-18",
    image:"/reports/dummypage-pic.jpg"
  }
]