export const students = [
  {
    class: "12",
    password: "BMHSAARI",
    dob: "2008-12-19",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class: "12",
    password: "BMHSABID",
    dob: "2009-03-19",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class: "12",
    password: "BMHSADHI",
    dob: "2008-06-04",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSAFRI",
    dob:"2008-03-17",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSALFI",
    dob:"2008-09-03",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSAMAR",
    dob:"2008-10-30",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSANLI",
    dob:"2008-07-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "12",
    password: "BMHSASKA",
    dob: "2008-05-13",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSATHI",
    dob:"2007-11-21",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSBHRA",
    dob:"2008-12-27",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSCHAN",
    dob:"2008-08-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSCLAR",
    dob:"2008-03-17",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "12",
    password: "BMHSDEVI",
    dob: "2008-10-14",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSDHAN",
    dob:"2009-06-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSDHAR",
    dob:"2009-03-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSDHAR",
    dob:"2008-02-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSDURA",
    dob:"2008-11-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSDURG",
    dob:"2008-01-03",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSGEET",
    dob:"2008-01-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSGIFT",
    dob:"2008-05-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSGODL",
    dob:"2008-08-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSGODS",
    dob:"2009-05-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSGOKI",
    dob:"2009-02-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSHARI",
    dob:"2008-07-13",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSHRIT",
    dob:"2008-09-25",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSISWA",
    dob:"2008-10-25",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSKANI",
    dob:"2008-11-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSKANI",
    dob:"2008-04-03",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "12",
    password: "BMHSKAVI",
    dob: "2009-03-22",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSLALI",
    dob:"2008-04-07",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSLIYA",
    dob:"2008-09-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSLUKE",
    dob:"2009-07-16",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSMARI",
    dob:"2008-12-21",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSMOHA",
    dob:"2008-04-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSMOHA",
    dob:"2008-12-27",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSMUHA",
    dob:"2008-05-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSMUHI",
    dob:"2009-02-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSNEER",
    dob:"2009-03-16",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSNIRU",
    dob:"2008-09-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSNIVE",
    dob:"2008-11-05",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSPAVI",
    dob:"2008-08-14",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSPRAB",
    dob:"2009-02-25",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSPRAK",
    dob:"2008-09-09",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSPRAV",
    dob:"2008-12-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSPREE",
    dob:"2009-03-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSRAHU",
    dob:"2008-12-16",
    image:"/reports/dummypage-pic.jpg"
  },
 {
    class:"12",
    password:"BMHSRISH",
    dob:"2007-08-18",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSSAIN",
    dob:"2008-09-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSAMM",
    dob:"2008-02-12",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSAND",
    dob:"2008-02-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSANG",
    dob:"2008-05-27",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSANK",
    dob:"2009-01-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSHAR",
    dob:"2008-10-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSIVA",
    dob:"2008-05-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSOUN",
    dob:"2008-11-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSSUBA",
    dob:"2008-06-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSTHEJ",
    dob:"2008-03-31",
    image:"/reports/dummypage-pic.jpg"
  },
   {
    class:"12",
    password:"BMHSVETR",
    dob:"2008-08-02",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"12",
    password:"BMHSYATH",
    dob:"2009-03-19",
    image:"/reports/dummypage-pic.jpg"
  }
]