export const students = [
  {
    class: "10",
    password: "BMSAADE",
    dob: "03042010",
    image: "/reports/X-B/AADESH_page-0001.jpg"
  },
  {
    class: "10",
    password: "BMSABIL",
    dob: "10022010",
    image:"/reports/X-B/ABILASH-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class: "10",
    password: "BMSABIN",
    dob: "21042010",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSADHI",
    dob:"24022010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSAGNE",
    dob:"03042010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSAISW",
    dob:"12062008",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSAKSH",
    dob:"06082010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "10",
    password: "BMSANDR",
    dob: "21082010",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSANUS",
    dob:"30112009",
    image:"/reports/X-B/ANUSH.V-PROGRESS-REPORT_page-0001.jpg" 
  },
  {
    class:"10",
    password:"BMSARUN",
    dob:"07042010",
    image:"/reports/X-B/ARUNKUMAR.E-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSASMI",
    dob:"20032010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSASNA",
    dob:"29062010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "10",
    password: "BMSASVI",
    dob: "05042011",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSATCH",
    dob:"07032010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSBALA",
    dob:"03112010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSBHAV",
    dob:"03112010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSBOWN",
    dob:"27022011",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSDARS",
    dob:"09082010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSDEEP",
    dob:"03112010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSDHAR",
    dob:"12042010",
    image:"/reports/X-B/DHARSHAN.K-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSDHAR",
    dob:"31102010",
    image:"/reports/X-B/DHARSHAN_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSDHYA",
    dob:"12112010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSESTH",
    dob:"02022011",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSFATH",
    dob:"29092010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSFATH",
    dob:"09042010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSGOMA",
    dob:"12082010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSHARI",
    dob:"24062009",
    image:"/reports/X-B/HARIASHWIN-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSHARI",
    dob:"03072010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "10",
    password: "BMSHARS",
    dob: "23122010",
    image: "/reports/X-B/HARSHIL_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSHASI",
    dob:"01062011",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSJEYA",
    dob:"27112009",
    image:"/reports/X-B/JEYARAJ_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSKANI",
    dob:"18012010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSMADH",
    dob:"12072010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSMANI",
    dob:"08052010",
    image:"/reports/X-B/MANIKANDAN.Y-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSMADH",
    dob:"09102010",
    image:"/reports/X-B/MADHAN.S-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSMONI",
    dob:"11112009",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSNAVE",
    dob:"07022009",
    image:"/reports/X-B/NAVEEN_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSNIVE",
    dob:"27052010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSPAUL",
    dob:"08052009",
    image:"/reports/X-B/Paul-Stephen-Selvakumar-Progress-Report_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSPRAN",
    dob:"03112010",
    image:"/reports/X-B/PRANAV_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSPRIY",
    dob:"11022011",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSPUSH",
    dob:"17042011",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSRAKA",
    dob:"09102010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSRAMY",
    dob:"18072010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSRAVI",
    dob:"02122010",
    image:"/reports/X-B/RAVIKIRAN-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSRITH",
    dob:"19122010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSRUTH",
    dob:"05032010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSSABA",
    dob:"06092010",
    image:"/reports/X-B/SABARI-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSSAIP",
    dob:"03072010",
    image:"/reports/X-B/SAI_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSSANJ",
    dob:"29062010",
    image:"/reports/X-B/SANJAY_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSSANT",
    dob:"01042011",
    image:"/reports/X-B/SANTHOSH.S-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSSARA",
    dob:"12082010",
    image:"/reports/X-B/SARATH-DEVAN-PROGRESS-REPORT_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSSATH",
    dob:"07022011",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSSTAC",
    dob:"15112010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSSWEA",
    dob:"24052010",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"10",
    password:"BMSTARA",
    dob:"10082009",
    image:"/reports/X-B/TARANATH_page-0001.jpg"
  },
  {
    class:"10",
    password:"BMSVISH",
    dob:"24022011",
    image:"/reports/dummypage-pic.jpg"
  }
]