export const students = [
  {
    class: "1",
    password: "BMHSABIS",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSARJU",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSARNO",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSBHAV",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSDHAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSDHAR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSDHAR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSDHAY",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSHARS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "1",
    password: "BMHSJAIS",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSJONO",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSJOSL",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSKANI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSKANI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSKAVI",
    dob:" ",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSKOWS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSLAKS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSLAKS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "1",
    password: "BMHSLITH",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMAST",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMATH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMEHB",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMOHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMUGA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "1",
    password: "BMHSMUHA",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSMUNI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSNANT",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSNEKA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSNITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "1",
    password: "BMHSNITH",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSNIVE",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSNIVE",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSPRAJ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSRAFA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSRANS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSREYA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSRITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSADH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "1",
    password: "BMHSSAIS",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSAJI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSAMY",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSHAS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSHER",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSHRE",
    dob:" ",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSIBI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSIME",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSIVA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "1",
    password: "BMHSSREE",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSREE",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSSTEP",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSTEJS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSTHAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSYASH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"1",
    password:"BMHSYOHI",
    dob:"2017-07-15",
    image:"/reports/dummypage-pic.jpg"
  }
]