export const students = [
  {
    class: "2",
    password: "BMHSADIT",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSAISH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSALAY",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSAMAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSANDR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSANEE",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSANUM",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSBALA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSBHAV",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSBHUV",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSBOOM",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSDANI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSDEEK",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSDEEN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSDENI",
    dob:" ",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSDHAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSDHAR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSGURU",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSHARI",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSHARI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSHARI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSHASH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSJASH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSJEFF",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSJERL",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSJERM",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSJESL",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSKANS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSKART",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSKAVI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSKEZI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSKIRI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSKOUS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSLALI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSMAGI",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSMINA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSMITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSMOHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSMUHA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSNITH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSNIVE",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSPAAR",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSPRAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSPRAN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSRABI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSRIAA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSRITH",
    dob:" ",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSRIYA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSRIYA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSRIYA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSRYAN",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSAHD",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSAIP",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSANJ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSANV",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSHAA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSHAS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSHAZ",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSREE",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSSUDH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "2",
    password: "BMHSSWAS",
    dob: "",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSTANS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSTHAR",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSTHEN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSVARN",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSVARS",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSYASH",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"2",
    password:"BMHSYOJI",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"SKG",
    password:"BMHSYUVA",
    dob:"",
    image:"/reports/dummypage-pic.jpg"
  }
]