export const students = [
  {
    class: "8",
    password: "BMHABIS",
    dob: "2008-12-08",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSADLI",
    dob:"2012-11-29",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSAHAL",
    dob:"2012-08-17",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSAISH",
    dob:"2011-09-26",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSAJIT",
    dob:"2012-05-01",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSAKIL",
    dob:"2012-10-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSAKSH",
    dob:"2012-04-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSALAN",
    dob:"2011-12-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSANUD",
    dob:"2012-10-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "8",
    password: "BMHSASHV",
    dob: "2011-09-10",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSASHW",
    dob:"2012-01-05",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSBHAV",
    dob:"2013-01-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSBROS",
    dob:"2011-09-27",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSCHIT",
    dob:"2012-10-27",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSDARS",
    dob:"2012-06-30",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSDEVA",
    dob:"2011-07-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSDHAN",
    dob:"2011-04-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSDHAR",
    dob:"2012-06-29",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "8",
    password: "BMHSDHAR",
    dob: "2012-06-01",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSGOBI",
    dob:"2012-11-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSHARI",
    dob:"2012-02-12",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSHARS",
    dob:"2012-08-01",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSHASI",
    dob:"2012-09-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSHATI",
    dob:"2012-08-30",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSKANI",
    dob:"2012-12-01",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSKAVI",
    dob:"2013-02-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSMALA",
    dob:"2013-01-28",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSMIDH",
    dob:"2012-09-14",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "8",
    password: "BMHSMOHA",
    dob: "2012-05-03",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSMOHA",
    dob:"2012-02-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSMUHA",
    dob:"2011-12-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSMURU",
    dob:"2012-06-25",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSNAVE",
    dob:"2012-05-07",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSNIKH",
    dob:"2012-10-18",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSNITH",
    dob:"2013-08-01",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSNITH",
    dob:"2012-11-15",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSPRAV",
    dob:"2013-01-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSRAGA",
    dob:"2011-10-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSRAKS",
    dob:"2012-10-16",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSRAMB",
    dob:"2011-12-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSRESH",
    dob:"2012-06-01",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSSATH",
    dob:"2012-08-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSSATH",
    dob:"2012-03-11",
    image:"/reports/dummypage-pic.jpg"
  },
    {
    class:"8",
    password:"BMHSSIVA",
    dob:"2012-03-15",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSSIVA",
    dob:"2012-11-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSSRUT",
    dob:"2012-03-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSSWEA",
    dob:"2012-02-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSTHAN",
    dob:"2012-09-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSTHIH",
    dob:"2012-10-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSTHIR",
    dob:"2012-02-23",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSVARU",
    dob:"2011-12-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"8",
    password:"BMHSYAZH",
    dob:"2012-05-08",
    image:"/reports/dummypage-pic.jpg"
  },
];
