export const students = [
  {
    class: "9",
    password: "BMHSAADH",
    dob: "2012-01-01",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class: "9",
    password: "BMHSABIS",
    dob: "2011-04-28",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class: "9",
    password: "BMHSADLY",
    dob: "2011-09-13",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSANJE",
    dob:"2011-11-07",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSASHI",
    dob:"2012-01-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSASMA",
    dob:"2011-02-25",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSDEEB",
    dob:"2011-03-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "9",
    password: "BMHSDEEP",
    dob: "2011-01-27",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSDEVA",
    dob:"2010-10-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSDURG",
    dob:"2011-03-23",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSFAIT",
    dob:"2011-04-02",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSGOPI",
    dob:"2011-08-26",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "9",
    password: "BMHSHARI",
    dob: "2011-01-19",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSHARS",
    dob:"2012-01-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSJAYA",
    dob:"2011-06-28",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSJENI",
    dob:"2011-06-18",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSKART",
    dob:"2010-11-22",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSKAVI",
    dob:"2011-07-17",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSLEVI",
    dob:"2011-07-09",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMADH",
    dob:"2011-10-19",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMADH",
    dob:"2011-08-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMANJ",
    dob:"2011-07-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMONI",
    dob:"2011-05-12",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMUHA",
    dob:"2011-12-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMUHA",
    dob:"2010-09-06",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSMUTH",
    dob:"2012-07-07",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSNAYA",
    dob:"2011-06-27",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSNITH",
    dob:"2011-10-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class: "9",
    password: "BMHSPRAD",
    dob: "2011-02-20",
    image: "/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSRAGA",
    dob:"2011-11-02",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSRAGU",
    dob:"2011-06-11",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSRAHU",
    dob:"2010-03-03",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSRITH",
    dob:"2011-04-05",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSROHI",
    dob:"2011-04-18",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSAAD",
    dob:"2011-11-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSACH",
    dob:"2010-03-15",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSANJ",
    dob:"2009-12-04",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSANJ",
    dob:"2011-06-25",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSARA",
    dob:"2011-07-21",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSHAM",
    dob:"2011-03-20",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSHAR",
    dob:"2011-09-30",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSRIR",
    dob:"2010-12-24",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSUBA",
    dob:"2010-08-29",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSUKA",
    dob:"2011-05-02",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSUMI",
    dob:"2011-05-10",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSSUYA",
    dob:"2011-11-08",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSVAAN",
    dob:"2011-08-23",
    image:"/reports/dummypage-pic.jpg"
  },
  {
    class:"9",
    password:"BMHSYASI",
    dob:"2011-05-18",
    image:"/reports/dummypage-pic.jpg"
  }
];
